volumes:
  pg_data:
  media:
  static:

# Перечень контейнеров:
services:
  postgres:
    # Из какого образа запустить контейнер:
    image: postgres:13
    # Файл (или список файлов) с переменными окружения:
    env_file: .env
    # Какой volume подключить для этого контейнера:
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    build: ./backend/
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - postgres
    volumes:
      - static:/app/collected_static
      - media:/app/media
  gateway:
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/media
  frontend:
    build: ./frontend/
    volumes:
      - static:/app/build